parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     live-con
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_encryption: ssl
    mailer_auth_mode:  login
    mailer_host:       smtp.gmail.com
    mailer_username:   flepeutrec
    mailer_password:   31051989

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    bootstrap_source:  http://twitter.github.com/bootstrap/assets/bootstrap.zip
    max_per_page:      20
